; Zexus for Revit - Inno Setup Script
; Supports Revit 2023, 2024, 2025, 2026
; net48 DLLs -> Revit 2023/2024 | net8.0 DLLs -> Revit 2025/2026
;
; To compile:
;   1. Install Inno Setup 6 from https://jrsoftware.org/isdl.php
;   2. Run build-installer.bat (or open this file in Inno Setup and click Compile)

#define MyAppName "Zexus for Revit"
#define MyAppVersion "0.2.0"
#define MyAppPublisher "Zhequan Zhang"
#define MyAppURL "https://github.com/QuanZ827/Zexus"

; Paths to build outputs (relative to this .iss file)
#define BuildNet48 "..\bin\Release\net48"
#define BuildNet8 "..\bin\Release\net8.0-windows"
#define AddinManifest "..\Zexus.addin"

[Setup]
AppId={{BAD31F3B-9E23-425C-A1B1-05E32B856E9E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
; Install staging area (not the final Addins folder)
DefaultDirName={commonappdata}\Zexus_Staging
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=Output
OutputBaseFilename=Zexus_Setup_v{#MyAppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
UninstallDisplayName={#MyAppName}
MinVersion=10.0
; Store uninstall info in a central location
UninstallFilesDir={commonappdata}\Zexus_Staging

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
WelcomeLabel2=This will install [name/ver] on your computer.%n%nSupports Revit 2023, 2024, 2025, and 2026.%nThe installer will auto-detect which versions are installed.%n%nRequirements:%n- At least one version of Revit (2023-2026) must be installed%n- You will need an Anthropic API key for first use%n%nClick Next to continue.

[Files]
; --- net48 DLLs (for Revit 2023 & 2024) - staged to {app}\net48 ---
Source: "{#BuildNet48}\Zexus.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.Buffers.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.Memory.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.Numerics.Vectors.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.Text.Encodings.Web.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.Text.Json.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}\net48"; Flags: ignoreversion
Source: "{#BuildNet48}\System.ValueTuple.dll"; DestDir: "{app}\net48"; Flags: ignoreversion

; --- net8.0 DLLs (for Revit 2025 & 2026) - staged to {app}\net8 ---
Source: "{#BuildNet8}\Zexus.dll"; DestDir: "{app}\net8"; Flags: ignoreversion
Source: "{#BuildNet8}\Zexus.deps.json"; DestDir: "{app}\net8"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#BuildNet8}\Zexus.runtimeconfig.json"; DestDir: "{app}\net8"; Flags: ignoreversion skipifsourcedoesntexist

; --- .addin manifest (staged) ---
Source: "{#AddinManifest}"; DestDir: "{app}"; Flags: ignoreversion

; --- team_config.json (optional, generated by build-installer.bat from api_key.txt) ---
Source: "team_config.json"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist

[Code]
var
  InstalledVersionsList: String;

function GetAddinsPath(RevitYear: String): String;
begin
  Result := ExpandConstant('{commonappdata}') + '\Autodesk\Revit\Addins\' + RevitYear;
end;

function IsRevitVersionPresent(RevitYear: String): Boolean;
begin
  Result := DirExists(GetAddinsPath(RevitYear));
end;

procedure CopyDirContents(SourceDir, DestDir: String);
var
  FindRec: TFindRec;
begin
  ForceDirectories(DestDir);
  if FindFirst(SourceDir + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
          begin
            CopyFile(SourceDir + '\' + FindRec.Name, DestDir + '\' + FindRec.Name, False);
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

procedure DeployToVersion(RevitYear: String; UseNet8: Boolean);
var
  AddinsPath, PluginDir, StagingDir, AddinFile: String;
begin
  AddinsPath := GetAddinsPath(RevitYear);
  PluginDir := AddinsPath + '\Zexus';

  // Clean old files first
  if DirExists(PluginDir) then
    DelTree(PluginDir, True, True, True);
  if FileExists(AddinsPath + '\Zexus.addin') then
    DeleteFile(AddinsPath + '\Zexus.addin');

  // Create plugin directory
  ForceDirectories(PluginDir);

  // Determine source staging dir
  if UseNet8 then
    StagingDir := ExpandConstant('{app}') + '\net8'
  else
    StagingDir := ExpandConstant('{app}') + '\net48';

  // Copy all DLLs from staging to plugin directory
  CopyDirContents(StagingDir, PluginDir);

  // Copy .addin manifest
  AddinFile := ExpandConstant('{app}') + '\Zexus.addin';
  CopyFile(AddinFile, AddinsPath + '\Zexus.addin', False);

  // Copy team_config.json if it exists (for team API key distribution)
  if FileExists(ExpandConstant('{app}') + '\team_config.json') then
    CopyFile(ExpandConstant('{app}') + '\team_config.json', PluginDir + '\team_config.json', False);

  Log('Deployed Zexus to Revit ' + RevitYear + ': ' + PluginDir);
  InstalledVersionsList := InstalledVersionsList + '    Revit ' + RevitYear + #13#10;
end;

function InitializeSetup(): Boolean;
var
  AnyFound: Boolean;
begin
  InstalledVersionsList := '';
  AnyFound := IsRevitVersionPresent('2023') or
              IsRevitVersionPresent('2024') or
              IsRevitVersionPresent('2025') or
              IsRevitVersionPresent('2026');

  if not AnyFound then
  begin
    if MsgBox('No Revit installation (2023-2026) was detected on this computer.' + #13#10 +
              'The Revit Addins folders were not found.' + #13#10#13#10 +
              'Do you want to install anyway?',
              mbConfirmation, MB_YESNO) = IDNO then
    begin
      Result := False;
      Exit;
    end;
  end;

  Result := True;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    // Deploy net48 DLLs to Revit 2023 and 2024
    if IsRevitVersionPresent('2023') then
      DeployToVersion('2023', False);
    if IsRevitVersionPresent('2024') then
      DeployToVersion('2024', False);

    // Deploy net8.0 DLLs to Revit 2025 and 2026
    if IsRevitVersionPresent('2025') then
      DeployToVersion('2025', True);
    if IsRevitVersionPresent('2026') then
      DeployToVersion('2026', True);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  i: Integer;
  Years: array[0..3] of String;
  AddinsPath, PluginDir: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    Years[0] := '2023';
    Years[1] := '2024';
    Years[2] := '2025';
    Years[3] := '2026';

    for i := 0 to 3 do
    begin
      AddinsPath := GetAddinsPath(Years[i]);
      PluginDir := AddinsPath + '\Zexus';
      if DirExists(PluginDir) then
        DelTree(PluginDir, True, True, True);
      if FileExists(AddinsPath + '\Zexus.addin') then
        DeleteFile(AddinsPath + '\Zexus.addin');
    end;
  end;
end;

function GetInstalledVersions(Param: String): String;
begin
  if InstalledVersionsList = '' then
    Result := '    (No Revit versions detected)'
  else
    Result := InstalledVersionsList;
end;

[Run]
Filename: "cmd"; Parameters: "/c echo. & echo ============================================ & echo   Zexus installed successfully! & echo. & echo   Installed for detected Revit versions. & echo. & echo   NEXT STEP: & echo   1. Open Revit (2023/2024/2025/2026) & echo   2. Click the Zexus button on the ribbon & echo   3. Click Settings to enter your API key & echo ============================================ & echo. & pause"; Description: "View setup instructions"; Flags: postinstall shellexec waituntilterminated
